FROM node:alpine


# RUN mkdir /usr/src/app

# RUN chmod -R 777 /usr/src/app

WORKDIR /usr/src/app

COPY package.json ./
#COPY --chown=node:node package.json ./
RUN npm install
# COPY --chown=node:node . .
COPY ./ ./


CMD ["npm","run","start"]